tools/readrpl/main.cpp

header.size includes the u32 decompressed size, which is read earlier. When an rpx (such as safe.rpx from Heath and Safety) with zlib compressed data at the very end is read, the inputstream will attempt to read past the end of the file and then error silently and no longer read, usually causing a segfault due to a null pointer for shStrTab.

Fix readrpl temp zlib buffer size

---

include/coreinit/expandedheap.h
include/coreinit/frameheap.h
include/coreinit/messagequeue.h
rpl/libcoreinit/exports.h

[These functions](https://gist.github.com/shinyquagsire23/14ee2d4272ce897340875964c17d5172) imported from wut do not exist in coreinit.rpl, as a result RPXs/RPLs with them in their imports will fail to load on hardware due to a check in loader.elf.

Remove imports which don't exist in elf2rpl's target coreinit version

---

crt/crt0.S
crt/memory.c
include/coreinit/internal.h
rpl/libcoreinit/exports.h
rules/ppc.mk
rules/rpl.ld
rules/rpl.mk
tools/elf2rpl/main.cpp

This PR fixes several issues with RPX building. The following are the particular fixes which this PR contains:
**rpl2elf**
- Search for imports before symbols, this prevents situations where a .data _stub symbol would override the actual import itself
- Convert RELATIVE relocations to ADDR32
- Divide .rela.dyn relocations into .rela.text, .rela.data, etc, and convert RELATIVE relocations to ADDR32
- Handle relocations where the symbol may not exist, but the offset is still within $TEXT or $DATA
- Fix corner cases with tempSize caused by the RELA section data being aligned to 64 bytes. tempSize is calculated in loader.elf as **(last_rela_offs + last_rela_size) - first_rela_offs**.
**libcrt**
- Stub __eabi instead of defining it, preventing any .got sections from being used with PIE
- Add …

Adjustments for linking, rpx/rpl generation

---

tools/elf2rpl/main.cpp

While reading symbols in relocations, findSymbol would sometimes select a symbol which ends up getting removed later on. By favoring symbols which will end up staying in the final RPL, this prevents that from happening.

Fix corner case with findSymbol in elf2rpl

---

tools/elf2rpl/main.cpp

Another fix on tempSize...
Sometimes the offsets for RELA sections, while being aligned to 64, end up way larger than the predicted size. So the best solution is probably just to assume worst-case alignment, since loader.elf is perfectly fine with larger values, it just errors out on smaller ones.

Assume largest possible size increase after alignment for tempSize

---

include/coreinit/screen.h
rpl/libcoreinit/exports.h

Basically what it says on the tin. OSScreen is useful for extremely basic homebrew since it can render fonts and give a straight framebuffer to work with.

Add OSScreen functions to coreinit

---

tools/elf2rpl/main.cpp

Issue only seemed to occur when importing multiple RPLs

Fix issue with import handling where import section symbols were indexed incorrectly

---

include/wut_types.h

This allows wut_types.h to be a drop-in replacement for gctypes.h from libogc, which several existing Wii U homebrew apps rely on.

Add additional type shorthands to wut_types.h

---

include/coreinit/foreground.h
include/proc_ui/procui.h
rpl/Makefile
rpl/libcoreinit/exports.h
rpl/libproc_ui/Makefile
rpl/libproc_ui/config.h
rpl/libproc_ui/exports.h

Adds additional imports for foreground management to libcoreinit, imports proc_ui.rpl for multitasking management. Some imports are missing due to being update to determine functionality/arguments. Required for #23

Add multitasking  support for wut

---

samples/helloworld/Makefile
samples/helloworld/src/main.c

No real point in forcing the user to use the Home Button Menu to exit when the app isn't doing much. Also a good example on exiting and switching apps using sysapp.

Have helloworld sample exit immediately using sysapp

---

rules/rpl.ld
tools/elf2rpl/main.cpp

- Fixes an issue where alignment in elf2rpl did not match up with the actual alignment of addresses
- Moves .tbss into .bss in the rpl linker script because GCC seems to like giving .tbss and .bss the same address for some reason.
- Remove unneeded sanity checks which false-fired with the addition of certain sections/relocations.

Multiple elf2rpl fixes

---

rpl/libcoreinit/fs_dev.c

Depending on how the allocations occur, path fixing can error at random due to bad length handling. File write buffers also used a sizeof on an allocated buffer which causes each write request to only be 4 bytes long, dramatically reducing write performance.

Fix ENAMETOOLONG handling, write buffer size in devoptab

---

README.md

A minor thing, but important to quickly get the projects in tools/ext

Add --recursive flag to usage instructions

---

tools/elf2rpl/main.cpp

Fixes compiling with -g where .debug_* sections would be created but not accounted for in tempSize, while loader.elf would count them and fail on a bounds check.

tempSize is based on all sections with a 0 address except RPL_CRCS and RPL_FILEINFO

---

Makefile
README.md
rpl/common/rules.mk
rules/ppc.mk
samples/helloworld/Makefile
samples/pong/Makefile

`uname -o` is not available on OS X, which is why I replaced it with an equivalent command. 
I did not test building on Cygwin, so it would be great if someone did that before merging this.
The helloworld example also wasn't building because of missing libs in the Makefile.
It's not much, but a start, I guess.

Allow wut to build on OS X, fix helloworld example makefile

---

include/gx2/clear.h
rpl/libgx2/exports.h

Removed functions did not exist in gx2.rpl causing loader.elf to error.

Remove GX2 functions which don't exist in target system version

---

rules/ppc.mk
rules/rpl.ld
rules/rpl.mk
tools/elf2rpl/main.cpp

Lets us use DevKitPPC without having changes over there, plus better optimization. Only downside is that .rodata is just kinda part of .text, but to be honest that's not that big of a deal I don't think.

Move rodata into text so that jump tables work properly without -fno-jump-tables

---

include/coreinit/cache.h
rpl/libcoreinit/exports.h
tools/Makefile
tools/elf2rpl/Makefile
tools/implcheck/Makefile
tools/implcheck/main.cpp
tools/readrpl/Makefile

While working on my current project (AutoBoot) I needed access to the function ICInvalidateRange. I added it to coreinit/cache.h, as I believe that would be where it belongs. This information is based on data already reversed by developers and is public on wiiubrew.org.
I also modified the makefiles to handle the creation of bin folders automatically, which didn't already happen. The lack of bin folders caused Xcode's clang compiler to fail building, so having the script automatically generate bin folders helps make the process a little more automated.

Added ICInvalidateRange to coreinit and modified Makefiles

---

README.md
samples/pong/CMakeLists.txt

The `CMakeLists.txt` file in the `samples/pong` directory specifies that all C source and header files in the `samples/pong` directory are to be included in the build. Because we do not specify that only the `src` folder should be used in the build, CMake also builds its compiler test programs and tries to link them with Pong. This results in `main()` being defined twice, which causes a linker error. This commit fixes that by filtering the build to only source files in the `src` directory.
You also missed a very important instruction in the README that had me stumped for a while (I don't build UNIX software often, hence why it took me a while to figure out). 😆

Pong: Fix build issues with CMake

---

samples/gx2/triangle/CMakeLists.txt
samples/gx2/triangle/src/main.c
src/crt/newlib.c
src/libwhb/include/whb/log_cafe.h
src/libwhb/src/log_cafe.c
src/libwhb/src/sdcard.c

This PR addresses a few issues that have been faced by both myself and issues that have been within the repo before.
Last month, you pushed changes to attempt fixing this issue. But it wasn't until I tried re-building from `master` yesterday that I found that your changes did not fix the issue. This PR includes (what I think is, at least) the proper fix for this issue. (see #55 for more details)
The GX2 Triangle demo had the line `WHBUnmountSdCard();` commented out because it froze the console when run. This is because the `FsCmdBlock` being used within that function is never initialised. As such, it will likely contain invalid data. I rectify this by calling `FSInitCmdBlock` before calling `FSUnmount`.
(I have also updated the triangle demo's CMake script to include new libraries …

Various small fixes

---

src/libwhb/src/crash.c

> whb: Add crash handler based off the one in coreinit.
> Although I'm not convinced it's actually working... yet.
This PR makes two small patches to the exception handling code present in `libwhb` which allow the exception handler to actually work, at least for me.
During handling of stack dumps, a loop is used to traverse the stack. Within the loop, it is checked whether or not the variable supposed to hold the stack pointer is either `null` or `0xFFFFFFFF`. However, at least for me, the entry at the bottom of the stack always has a back-chain value of `0x1` which is not handled by this loop. As such, the handler attempts to read data from `0x1`, causing another exception. The fix for this was to consider `0x1` to be the end of the stack, in addition to `null` and `0xFFFFFFFF`.
After …

libWHB exception handler now works

---

cmake/wut-toolchain.cmake

This allows WUT to successfully operate within a path that contains spaces.
I discovered this when I was attempting to build my current project on Windows, in which my home directory contains spaces. (that was a good idea, eh?)

wut-toolchain: Properly escape include/lib paths

---

share/wut.toolchain.cmake

Heyo! Just a small thing - using include_directories instead of `-I`.
This helps some cmake analysers and the like to better get an idea of how wut works, while having the same effect in terms of actual compiling. In my case, it meant the IDEs I was experimenting with would find wut's headers without extra help!
If there's some reason this wasn't done initially, I'd be glad to hear it. Not too attached to this change, though it would be nice ;D
Thanks again!
-Ash

cmake: Use include_directories instead of -I cflags

---

include/coreinit/memorymap.h
include/nn/ac.h
include/nn/ac/ac_c.h
include/nn/ac/ac_cpp.h
include/nn/nn.dox
include/nn/result.h
include/nn/swkbd.h
include/nn/swkbd/swkbd_cpp.h
include/swkbd/rpl_interface.h
include/swkbd/swkbd.dox
include/sysapp/launch.h
include/sysapp/switch.h
include/sysapp/title.h

Heyo!
Another round of documentation updates, big-ticket one here is swkbd. I know it hasn't been fully RE'd yet, but the example was good enough to get the important functions done! Also chucked in nn::ac and nn::Result for good measure; since doxygen's C++ layout is a little weird and it made sense to have the index pages look better.
devkitPro peeps - I usually do this branch/PR thing so exjam has a chance to catch any mistakes (it's happened before!) Sorry if you get an email about it.
-Ash

docs: Add documentation for swkbd, ac; minor updates for sysapp documentation

---

share/wut.mk

Fixes compilation errors with makefile after the change of elf2rpl and rplexportgen path

makefile: Update wut-tools path

---

libraries/wutdevoptab/devoptab_fs_stat.c

The double free caused apps to crash when attempting to run stat on a directory

devoptab: Fix double free in __wut_fs_stat

---

include/coreinit/debug.h

- add function OSIsDebuggerInitialized
- add function OSIsDebuggerPresent
- add function OSIsECOBoot
- add function OSIsECOMode

Add missing functions to coreinit/debug.h

---

include/coreinit/userconfig.h
tests/test_compile_headers_common/test_compile_headers_list.h

- add enum UCCommand
- add enum UCDataType
- add enum UCErrors
- add enum UCFileSys
- add struct UCSysConfig
- add struct UCAsyncParams
- add function UCOpen
- add function UCClose
- add function UCDeleteSysConfig
- add function UCDeleteSysConfigAsync
- add function UCReadSysConfig
- add function UCReadSysConfigAsync
- add function UCWriteSysConfig
- add function UCWriteSysConfigAsync
See decaf for reference:
- https://github.com/decaf-emu/decaf-emu/blob/b75f646a1ec30dfb82eddd0ddf8f2327b729f699/src/libdecaf/src/cafe/libraries/coreinit/coreinit_userconfig.h
- https://github.com/decaf-emu/decaf-emu/blob/407f3f809322becfa05b1cdfe900216d78beef55/src/libdecaf/src/ios/auxil/ios_auxil_enum.h

Add coreinit/userconfig.h

---

include/coreinit/memory.h

(already exist in coreinit/cache.h)

Coreinit: Remove duplicate function (OSMemoryBarrier) 

---

include/nn/pdm.h
include/nn/pdm/pdm_c.h
include/nn/pdm/pdm_cpp.h
tests/test_compile_headers_common/test_compile_headers_list.h

I started reverse engineering the `nn_pdm.rpl`. 
There are still some functions missing (like the Set functions) but I couldn't figure out how to use them.
I did my best at documenting what they do.
The `nn_pdm.rpl` is used by the Daily Log for getting the data about playing times and by some other executable's and lib's.
I also don't know what `PlayLog` and `PlayEvent` are for.
I found all of this out by looking at disassembled code and by looking at the save files located under `mlc/usr/save/system/pdm`.

Add some nn_pdm.rpl headers

---

libraries/wutdevoptab/devoptab_fs.c

It may be useful for an application to call to (de)-init the devoptabs multiple times

wutdevoptab: Reset `__wut_fs_initialised` and `__wut_devoptab_fs_client` in `__fini_wut_devoptab`

---

include/nn/pdm/pdm_cpp.h
include/vpad/input.h

Add definitions for
- VPADGetGyroZeroDriftMode
- VPADSetGyroZeroDriftMode
- VPADGetGyroDirReviseParam
- VPADSetGyroDirReviseParam
- VPADStartGyroMagRevise
- VPADStopGyroMagRevise
- VPADGetTVMenuStatus
- VPADSetTVMenuInvalid

Add more VPAD definitions

---

libraries/libwhb/include/whb/file.h
libraries/libwhb/src/file.c
libraries/libwhb/src/sdcard.c

WHB is adding FSClients but never deletes them. 
Faulty FSClient entries may lead to crashes when trying to add a new client.
Normaly this is not a problem because the memoy is cleared when exiting an application, but when chainloading multiple payloads previous FSClients may be overriden and therefore corrupted. When a corrupted FSClient is still added, adding new clients will crash the console.
Example crash dump:
```
Core1: Instruction at 0x010670E0 (from SRR0) invalid access of 0x00001614 (value from DAR)
00;00;17;710: 
--Proc15-Core1--------- OSContext 0x100457E0 --------------------
00;00;17;710: tag1  = 0x4F53436F (expecting 0x4F53436F)
00;00;17;710: tag2  = 0x6E747874 (expecting 0x6E747874)
00;00;17;710: TBR   = 0x00000000_2BA7A7A2
00;00;17;710: CR    = 0x84200024
INFO: nn::ipc …
```

WHB: Fix missing FSDelClient calls

---

libraries/wutnewlib/wut_clock.c
libraries/wutnewlib/wut_clock.h
libraries/wutnewlib/wut_gettod_r.c

It currently uses OSCalendarTime.tm_sec which contains the seconds of the current minute from 0-59 and not the seconds since the epoch.

wutnewlib: fix gettod implementation

---

libraries/libwhb/include/whb/log_module.h
libraries/libwhb/src/log.c
libraries/libwhb/src/log_module.c

Aroma will have  the concepts of "modules" will can exports functions like system rpls do.  There will be a module for logging and this PR is implementing support for it.
Advantages of outsourcing the actual logging implementation into a module:
- Can be updated/replaced without recompiling every homebrew
- In combination of a plugin it would be even possible to have some runtime implementation
- This avoids that every homebrew/module/plugins will need to bring they own logging implementation (e.g. via udp), which reduces filesizes. (simple modules which used `WHBLogUdpInit()` are now 5KiB instead of 45KiB)
Recommended usage:
Currently Aroma is not release and there are use cases where Aroma (and so also the LoggingModule) is simply not available. If this a possible scenario for the …

Add support for a upcoming LoggingModule

---

include/coreinit/launch.h

This one is pretty simple. `OSForceFullRelaunch()` followed by `SYSLaunchMenu()` is a common function pairing from what I can tell. For example, the Haxchi installer calls this pair of functions just before closing if a title has been patched. `SYSLaunchMenu()` is already declared in include/sysapp/launch.h, so `OSForceFullRelaunch()` should probably be included as well.
I wasn't sure where best to add this function. I knew it should go somewhere in include/coreinit, but I couldn't find an appropriate file to add it to. In the end, I opted to add it to a new header file on its own for now, as that seemed like the best option. If there's a better place to put this, let me know and I can update this.

Add OSForceFullRelaunch() declaration

---

Makefile
include/erreula/erreula.dox
include/erreula/rpl_interface.h
include/nn/erreula.h
include/nn/erreula/erreula_cpp.h
include/padscore/kpad.h
include/padscore/wpad.h
libraries/nn_erreula/nn_erreula.cpp
libraries/nn_swkbd/nn_swkbd.cpp
samples/cmake/CMakeLists.txt
samples/cmake/erreula/CMakeLists.txt
samples/cmake/erreula/main.cpp

erreula.rpl is wrapped by a small static library called nn::erreula, similar to swkbd.
I copied the nn::erreula wrapper from a game which included debug symbols - the same as what I did for swkbd

Add nn::erreula library.

---

.github/workflows/doc.yml

This PR will publish the doxygen documentation to GitHub Pages when pushing ~~to the master branch~~ a tag.
With the current wut project configuration, this PR is a bit useless. Right now the GitHub Pages is set to use a Custom domain. So when you go to https://devkitPro.github.io/wut you are redirected to https://wut.devkitpro.org.
If you want to keep this behavior:
1. I would recommend to delete the [gh-pages](https://github.com/devkitPro/wut/tree/gh-pages) branch so we know it's not use
2. I would also update the doc on the server to have the latest version
3. And of course I would close this PR
If not... please accept this PR and change the GitHub Pages project Settings 😁

Publish documentation when pushing to a tag

---

include/sysapp/switch.h

- Add missing return types (probably >= 0 on success)
- Add missing arguments for existing functions
- Complete incomplete types
- Add missing functions
- add missing types

sysapp: Fix return types and arguments for switchTo-functions, add missing switchTo-fucntions

---

include/coreinit/threadqueue.h

`next` and `prev` were swapped for some reason, see [decaf](https://github.com/decaf-emu/decaf-emu/blob/6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6/src/libdecaf/src/cafe/libraries/coreinit/coreinit_thread.h#L74)

coreinit: Fix OSThreadLink struct

---

include/coreinit/filesystem.h
libraries/wutdevoptab/devoptab_fs_chmod.c

This also fixes the missing chmod mode translation in the devoptab

coreinit: Add missing parameter to FSChangeMode/FSChangeModeAsync

---

libraries/wutdevoptab/devoptab_fs.c

We need to make sure FSUnmount is only called with a valid target. Calling FSUnmount with an invalid target causes the FS to throw fatal error, softlocking the whole console:
```
00;02;09;520: FS: FSUnmount: target specifies invalid mount path.
00;02;09;520: FS: Updated volume state of client 0x80cfbd80 to FS_VOLSTATE_FATAL(10)
00;02;09;520: FS: by error -196641.
00;02;09;520: FS: Fatal error occured.
```

wutdevoptab: Only call FSUnmount if FSMount was successful

---

libraries/wutdevoptab/devoptab_fs_mkdir.c
libraries/wutdevoptab/devoptab_fs_utils.c

The FSError values are only used for `FSSetEmulatedError` and `FSGetEmulatedError` to emulate fs errors (and interally in the FSClient struct). 
**No FS function is ever returning FSError values.** 
This PR removes the mapping for all FSError values, fixes the `FS_STATUS_CANCELLED` mapping, and add the mapping for the missing FSStatus values.
I couldn't find a matching value for FS_STATUS_ALREADY_OPEN, FS_STATUS_CORRUPTED and FS_STATUS_FATAL_ERROR so I decided to return EIO, not sure if there is a better option

wutdevoptab: Replace FSError usage with FSStatus in __wut_fs_translate_error

---

libraries/wutnewlib/wut_newlib.c

Fixes for example usage of `std::chrono::high_resolution_clock::now()`

Fix syscall_clock* implementation

---

include/gx2/registers.h

Copied from [decaf-emu](https://github.com/decaf-emu/decaf-emu/blob/75993f0a6d2b030485e2d01404786614a2b5fbea/src/libdecaf/src/cafe/libraries/gx2/gx2_registers.h#L594-L606) (renamed `rasteriser` to `rasterizer` to match function name).

gx2: Add clip control functions

---

libraries/wutdevoptab/devoptab_fs.h
libraries/wutdevoptab/devoptab_fs_fstat.c
libraries/wutdevoptab/devoptab_fs_stat.c
libraries/wutdevoptab/devoptab_fs_utils.c

- `stat` is now implemented with a single FSGetStat call instead of doing multiple calls.
- Sets the mode properly instead of guessing it
- Sets st_atime, st_ctime and st_mtime
Code snippets were taken from [this PR](https://github.com/wiiu-env/libiosuhax/pull/59) by @Crementif

wutdevoptab: Add time and mode information for stat and fstat

---

share/wut.ld

The CafeOS loader skips import sections when calculating the lower bounds of loader info (see [decaf-emu](https://github.com/decaf-emu/decaf-emu/blob/6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6/src/libdecaf/src/cafe/loader/cafe_loader_setup.cpp#L478)).
This ends up using symtab for the lower bound which comes after the imports, resulting in a negative offset [here](https://github.com/decaf-emu/decaf-emu/blob/6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6/src/libdecaf/src/cafe/loader/cafe_loader_setup.cpp#L318).
This PR adds a dummy section (which is not using the import type) before the imports in loadmem, which makes sure the lower bounds stay correct.

Add wut_load_bounds section to prevent loader bug

---

include/coreinit/filesystem.h

A few FSError values are off by 0x10. See IOSU @0x1071209c for reference.

coreinit: Fix FSError enum

---

include/sysapp/title.h

0 returns the title id of the **Wii U Menu** (the one where you launch the games and apps) not the Home Menu (the menu that appears when you press the HOME button)

sysapp: Fix incorrect enum name

---

libraries/wutdevoptab/devoptab_fs_seek.c

At the moment the offset if updated even if the actual seek fails

wutdevoptab: Only update the file->offset on a successful seek.

---

libraries/wutdevoptab/devoptab_fs_utils.c

In some cases flags for the file/dir are not set, but we can determine the type based on the size. 
E.g. `/vol/external01` can be opened via FSOpenDir but FSGetStat (and friends) don't set `FS_STAT_DIRECTORY`. In other cases (e.g. reading files from discs) there a similar problem where the filesize is not, but not `FS_STAT_FILE`

wutdevoptab: Fix setting mode flags in edge cases

---

libraries/wutdevoptab/devoptab_fs.c
libraries/wutdevoptab/devoptab_fs.h
libraries/wutdevoptab/devoptab_fs_getmtime.c
libraries/wutdevoptab/devoptab_fs_utimes.c

Some functions return a undefined return code if they are not implemeted properly. See [here](https://github.com/devkitPro/newlib/blob/devkitPPC/libgloss/libsysbase/lstat.c#L14) and [here](https://github.com/devkitPro/newlib/blob/devkitPPC/libgloss/libsysbase/utime.c#L12)

wutdevoptab: Fix undefined behaviour for unimplemented function

---

Makefile
libraries/wutcrt/crt0_rpl.s
libraries/wutcrt/crt0_rpx.s
libraries/wutcrt/wut_crt.c
libraries/wutcrt/wut_preinit.c
libraries/wutdefaultheap/wut_defaultheap.c
libraries/wutmalloc/wut_malloc.c
libraries/wutnewlib/wut_malloc_lock.c
libraries/wutnewlib/wut_newlib.c
libraries/wutnewlib/wut_sbrk.c

Wut currently uses wutmalloc as a wrapper around the default CafeOS heap functions (`MEMAllocFromDefaultHeap` / `MEMFreeToDefaultHeap`).
This default heap is really slow for large amounts of allocations, which causes lots of slowdowns. A lot of retail games use a fast custom heap to prevent this issue.
This draft uses the malloc implementation in newlib instead and replaces the default heap functions with a wrapper around the newlib functions (see wutdefaultheap).
This is currently marked as a draft since it's a somewhat major change and there might be potential issues resulting from this which I haven't thought of.
RPX files now implement and export a `__preinit_user` function, which will be called before any allocations are done to allow replacing the `MEMAllocFromDefaultHeap` / …

Replace the CafeOS default heap with a custom one

---

cafe/nn_acp.def
include/nn/acp/title.h

Previously getting metaXML didn't work when the ACPMetaXml ptr was not aligned to 0x40, this implementation enforces the correct alignment.

nn_acp: Add ACPMetaXml parameter alignment check

---

include/coreinit/filesystem.h

See [decaf](https://github.com/decaf-emu/decaf-emu/blob/6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6/src/libdecaf/src/cafe/libraries/coreinit/coreinit_fs_cmdblock.h#L282). I was about to add the whole struct, but circular includes got way to annoying so I gave up and only added the field I use =(

coreinit: Update FSCmdBlockBody struct to include asyncResult

---

libraries/wutcrt/wut_crt.c

A debugger like [Wii-U-Debugger](https://github.com/kinnay/Wii-U-Debugger) is triggered by a trapword. To allows debugging of homebrew .rpx this PR will add the `OSIsDebuggerInitialized`-check thats present in all retail titles to the CRT

wutcrt: Add a trapword in case a debugger is initialized to allow debugging

---

libraries/wutdevoptab/devoptab_fs.h
libraries/wutdevoptab/devoptab_fs_open.c
libraries/wutdevoptab/devoptab_fs_write.c

In order to keep our "file offset" and real file offset in sync, we need to update the file->offset to the current filesize on each write if O_APPEND is set.

wutdevoptab: Fix "syncing" the file->offset with the real offset on append mode.

---

libraries/wutdevoptab/devoptab_fs_seek.c

Avoid FSSetFilePos call if the position is not changing anyway.

wutdevoptab: Return early in lseek when the position is not changing

---

libraries/wutnewlib/wut_lock.c
libraries/wutnewlib/wut_sbrk.c
libraries/wutstdc++/wut_gthread_once.cpp

- Replaces the usage of the built-in atomics with the OS* atomics from coreinit.
This avoids a hardware bug described [here](https://fail0verflow.com/blog/2014/console-hacking-2013-omake/).
> There appears to be a bug that affects load-exclusive and store-exclusive instructions (an explicit cache flush is required)
The gcc built-in atomics do not emit a cache flush which might cause issues in the current wut lock implementation.
- Uses `OSSwapAtomic` in wutstdc++'s once implementation where a compare isn't necessary.
- Uses `OSCompareAndSwapAtomicEx` to directly update the oldSize in the newlib `sbrk` implementation.

Fix and improve usage of atomics

---

libraries/wutdevoptab/devoptab_fs_open.c

The target file when calling `std::filesystem::copy_file` opens the file with `O_CREAT | O_WRONLY | O_EXCL`. This PR adds supports for the `O_CREAT | O_WRONLY` flag-combination and add a checks for `O_EXCL`

Implement support for more flags (combinations) when opening files with the devoptab

---

include/avm/drc.h
include/gx2/display.h
include/gx2/enum.h
include/vpad/input.h
libraries/libwhb/src/gfx.c

Allows making use of the MultiDRC mode, which can be enabled with the functions from #264 and #265.
Not sure what `GX2_SCAN_TARGET_TV1` is used for, from RE'ing GX2 it seems to copy the colorbuffer to some TV scanbuffer.
`GX2GetSystemDRCScanMode` was replaced with `GX2GetSystemDRCMode` in WhbGfx since `GX2GetSystemDRCScanMode` doesn't seem to keep the second GamePad in mind.

Add several definitions for Multi/Double DRC mode

---

include/coreinit/im.h
tests/test_compile_headers_common/test_compile_headers_list.h

Mostly from [decaf-emu](https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/cafe/libraries/coreinit/coreinit_im.h).
Moved `IMHomeButtonParams` to a struct, added `IMEvent`, `IM_GetEventNotify`, and `IM_CancelGetEventNotify`.

Add missing IM_* functions from coreinit

---

include/coreinit/filesystem.h
include/coreinit/filesystem_fsa.h

Structs taken from [decaf](https://github.com/decaf-emu/decaf-emu).
See [FSAReponse](https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/ios/fs/ios_fs_fsa_response.h) and [FSARequest](https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/ios/fs/ios_fs_fsa_request.h)

Add missing FSARequest/FSAResponse structs

---

libraries/wutstdc++/wut_gthread_thread.cpp

We should return an error when allocating memory. This allows us to catch a exception instead of crashing.

wutstdc++: Check if memory allocations were successful on thread creation

---

include/nn/result.h

From [decaf-emu](https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/nn/nn_result.h#L41-L47).

nn::Result: add missing modules

---

libraries/wutdevoptab/devoptab_fs_read.c
libraries/wutdevoptab/devoptab_fs_write.c

If the size is < 0x40 we need to use the aligned buffer anyway, so we check this first to avoid splitting the call up into multiple calls.
Example:
With the **previous** implementation writing 26 bytes from buffer 0x10000038, will result two write calls.
First call writes 8 bytes (buffer not aligned => `MIN(size, 0x40 - ((uintptr_t) ptr & 0x3F)`), the other one the remaining 18 bytes (buffer is now aligned, but size is now < 0x40).
With the **new** implementation the same operation (write 26 bytes from 0x10000038) would just result in one single 26 bytes (because `size < 0x40` is checked first) call.

wutdevoptab: check size of a read/write before checking the buffer alignment to reduce the read/write calls

---

include/nn/nfp/nfp_cpp.h

This PR includes the following:
- Adds documentation for functions and structs
- Adds `GetNfpAdminInfo` and the `AdminInfo` struct
- Adds several more result descriptions
- Updates struct names to match the ones found in the amiibo javascript extension, which several games are using
- Minor fixes to match wuts coding style

nn_nfp: Update functions, structs and add documentation

---

libraries/wutstdc++/wut_gthread.h
libraries/wutstdc++/wut_gthread_thread.cpp

At the moment the default stack size for threads is 4MiB, which seems to be way to much. Especially if you use threads in aroma modules/plugins where memory will be very limited (only ~60MiB for all plugins/modules code, data and heap).
For reference: The stack size for the default Cafe OS thread is 64Kib.
The actual value for the new stack size is open for discussion

wutstdc++: Decrease the stack size for gthread threads from 4 MiB to 128 KiB

---

libraries/wutstdc++/wut_gthread_cond.cpp

The epoch for the timeout needs to be converted from 1970 back to 2000.

wutstdc++: Fix __wut_cond_timedwait

---

libraries/libwhb/src/console.c

Previously input strings with the length == LINE_LENGTH considered "okay", but lead to a to out of bounce write (`sConsoleBuffer[sLineNum][length] = 0;`)

libwhb: Fix length check in ConsoleAddLine

---

Makefile
include/nsysccr/irda.h
include/vpad/input.h
libraries/libirc/include/irc/cdc.h
libraries/libirc/include/irc/irc.h
libraries/libirc/src/cdc.c
libraries/libirc/src/irc.c
tests/test_compile_headers_common/test_compile_headers_list.h

This adds functionality to use the IR hardware in the GamePad.
Unfortunately there isn't a library for IR connections in OSv10. This PR reimplements the IRC library used by some titles, which is used to create IR connections.
Note that the GamePad itself enforces data to follow a specific (proprietary?) protocol, so data will always be sent with a header and an appended checksum. Received data is also expected to follow this format.
Closes #106.

Add IR support

---

include/coreinit/dynload.h

Se decaf:
https://github.com/decaf-emu/decaf-emu/blob/6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6/src/libdecaf/src/cafe/libraries/coreinit/coreinit_dynload.cpp#L40

coreinit: Add missing (internal) structs

---

include/coreinit/codegen.h

See decaf:
https://github.com/decaf-emu/decaf-emu/blob/6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6/src/libdecaf/src/cafe/libraries/coreinit/coreinit_codegen.h#L8

coreinit: add OSGetCodegenVirtAddrRange

---

include/coreinit/context.h
include/coreinit/thread.h

See Cemu for reference:
<https://github.com/cemu-project/Cemu/blob/f3ff919be25189dcf4a0120b48360bb415d7b86c/src/Cafe/OS/libs/coreinit/coreinit_Thread.h#L37>
<https://github.com/cemu-project/Cemu/blob/f3ff919be25189dcf4a0120b48360bb415d7b86c/src/Cafe/OS/libs/coreinit/coreinit_Thread.h#L364-L369>
<https://github.com/cemu-project/Cemu/blob/f3ff919be25189dcf4a0120b48360bb415d7b86c/src/Cafe/OS/libs/coreinit/coreinit_Thread.h#L439>

coreinit: Add missing fields and enum definitions to OSThread and OSContext

---

include/coreinit/dynload.h

== DETAILS
This commit provides two tweaks:
1. Add the "library not found" error, value of -6, to the `OSDynLoad_Error` enums
2. Define an `OSDynLoad_ExportType` enum and use it in place of the `isData` boolean parameter to avoid raw `true`/`false` values in the code and make usages easier to read:
```c
// before - unclear what "false" means in this context
last_error = OSDynLoad_FindExport((OSDynLoad_Module)lib, false, proc, &ptr_sym);
```
vs:
```c 
// after - aha, we're looking up a function symbol 
last_error = OSDynLoad_FindExport((OSDynLoad_Module)lib, OS_DYNLOAD_EXPORT_FUNC, proc, &ptr_sym);
```

A little fleshing out of the dynamic library header

---

include/coreinit/dynload.h

Should be LOAD=1 and UNLOAD=2. Checked with coreinit.rpl
Decaf also has it defined as 1 and 2 in the [EntryReason](https://github.com/decaf-emu/decaf-emu/blob/e8c9af3057a7d94f6e970406eb1ba1c37c87b4d1/src/libdecaf/src/cafe/libraries/coreinit/coreinit_enum.h#L95-L98) enum

coreinit: Fix OSDynLoad_EntryReason values

---

include/coreinit/kernel.h

See decaf:
https://github.com/decaf-emu/decaf-emu/blob/6feb1be1db3938e6da2d4a65fc0a7a8599fc8dd6/src/libdecaf/src/cafe/kernel/cafe_kernel_info.h#L22

coreinit: Add KernelInfo0/KernelInfo6 structs

---

include/vpad/input.h
include/vpadbase/base.h
include/vpadbase/vpadbase.dox
libraries/libirc/include/irc/irc.h
libraries/libirc/src/cdc.c
tests/test_compile_headers_common/test_compile_headers_list.h

This separates the `VPADBASE` functions from `vpad/input.h` into their own header.
They're two separate libraries on the system and this change makes this more clear.

Separate vpadbase from vpad

---

libraries/wutdevoptab/devoptab_fsa.h

Testing with gcc 13 this code is missing header for snprintf. Adding cstdio for that & switching to other c++ headers.

devoptab_fsa: use c++ headers

---

include/coreinit/thread.h
libraries/wutnewlib/wut_newlib.c
libraries/wutnewlib/wut_newlib.h
libraries/wutnewlib/wut_reent.c
libraries/wutstdc++/wut_gthread.h

Currently all threads share the same reent.
This implements the getreent syscall using thread specifics to ensure each thread has its own reent.

Implement __syscall_getreent

---

include/coreinit/alarm.h
include/coreinit/thread.h

Most of the fields are coming from [decaf](https://github.com/decaf-emu/decaf-emu/blob/master/src/libdecaf/src/cafe/libraries/coreinit/coreinit_thread.h).
Changes compared to decafs struct:
- the `eh_*` fields have been extracted into a seperate struct. The thread init function does a memset for 0x1D8 bytes at offset 0x3A0, this indicated an own struct. First 0x68 bytes are still unknown.
- `stackSyncObjAllowed` has been added (but is only used on debug builds, and only for logging)
- The final 20 bytes (now defined as `reserved`) are cleared by the thread init functions but never used. These are probably just unused reserved bits.

coreinit: Add some missing field to the OSThread struct

---

libraries/wutnewlib/wut_reent.c
libraries/wutnewlib/wut_thread_specific.c
libraries/wutnewlib/wut_thread_specific.h
libraries/wutstdc++/wut_gthread.h
libraries/wutstdc++/wut_gthread_keys.cpp

Alternative solution to the problem described in #323.
This approach uses a custom implementation of the `OSGetThreadSpecific`/`OSSetThreadSpecific` function which can be overriden by WUMS/WUPS.

Implement wut_set_thread_specific/wut_get_thread_specific as weak functions

---

libraries/wutdevoptab/devoptab_fsa_open.cpp

**(O_EXCL | O_CREAT | O_RDWR) and (O_EXCL | O_CREAT | O_WRONLY)**
Currently every `O_CREAT` needs a `O_TRUNC` as well because Cafe OS truncates the file when opened with `w` and `w+`. When `O_EXCL` is set this doesn't matter because we never touch (truncate) existing files. 
**O_CREAT | O_RDWR**
Very similar to `O_CREAT | O_WRONLY`

wutdevoptab: Add support for opening files with more flag combinations

---

include/gx2/enum.h

This adds various enum values some of which are based on [decaf-emu's SQ register enums](https://github.com/decaf-emu/decaf-emu/blob/dd0b1be35849c5bed7d7cdb60125a996620da785/src/libgpu/latte/latte_enum_sq.h).
See:
- Value returned by `GX2RGetBufferAlignment(GX2R_RESOURCE_BIND_UNIFORM_BLOCK)`
- <https://github.com/decaf-emu/decaf-emu/blob/dd0b1be35849c5bed7d7cdb60125a996620da785/src/libdecaf/src/cafe/libraries/gx2/gx2_enum.h#L13>
- <https://github.com/decaf-emu/decaf-emu/blob/dd0b1be35849c5bed7d7cdb60125a996620da785/src/libgpu/latte/latte_enum_cb.h#L28-L29> 
- <https://github.com/decaf-emu/decaf-emu/blob/dd0b1be35849c5bed7d7cdb60125a996620da785/src/libgpu/latte/latte_enum_sq.h#L306-L315>
- <https://github.com/decaf-emu/decaf-emu/blob/dd0b1be35849c5bed7d7cdb60125a996620da785/src/libgpu/latte …

Add missing GX2 enum values

---

cafe/nsysnet.def
include/netinet/in.h
include/netinet/tcp.h
include/nsysnet/misc.h
include/sys/socket.h
libraries/wutsocket/wut_socket_common.c
tests/test_compile_headers_common/test_compile_headers_list.h

This adds a define for all `setsockopt`/`getsockopt` optnames supported on the IOSU-side implementation, which includes support for multicast. 
Calling `set_multicast_state(TRUE)` is required for sending multicasts, otherwise `bind` and `sendto` fail with `ENETUNREACH` for multicast addresses.

Add missing optnames and multicast support

---

include/proc_ui/procui.h

While testing my aroma plugin I found out ProcUIInForeground wasn't working as I expected, which led me to checking it out in ghidra. While there I thought I would also check out ProcUIIsRunning.

procui: Fix ProcUIInForeground and ProcUIIsRunning comments

---

share/wut_rules

When using the make option `GENERATE_COMPILE_COMMANDS=1`, it will generate the compile commands database but never run the `end` command, so the filename will be stuck as `compile_commands.part`. This change fixes it so `compile_commands.json` is the final filename.
I referenced how it's done for 3DS: https://github.com/devkitPro/devkitarm-rules/blob/ab0f5c46edaf0d3e7d582bf0e66430dbde92a902/3ds_rules#L43

Finalize compile commands

---

include/nn/erreula/erreula_cpp.h
include/nn/swkbd/swkbd_cpp.h

See title. Values taken from [Cemu](https://github.com/cemu-project/Cemu/blob/f3c95f72e74d8a5f5873061fbb994643c63ec9c5/src/config/CemuConfig.h#L158) and reverse engineering nn::swkd (e.g. for the restricted nn::swbkd LanguageType/RegionType values)
See: #335

Add missing language/region values to nn::erreula and nn::swkbd

---

.github/workflows/doc.yml

The Doxygen version packaged for ubuntu-20.04 seems to cause some preprocessing bugs.

docs: Bump runner version

---

libraries/wutnewlib/wut_newlib.c

Provides custom abort and assert_func implementation to display some text on the screen (and gamepad). Previously a failed assertion (or calling abort) would just softlock the console without giving the user/dev any form of feedback.

wutnewlib: implement abort, assert and assert_func

---

include/avm/avm.dox
include/avm/config.h
include/avm/tv.h
include/tve/tve.dox
include/tve/tve.h
tests/test_compile_headers_common/test_compile_headers_list.h

My first big PR here so I expect you'll have some suggested changes for me but hopefully most of it is OK.

Add AVM and TVE headers, functions and enums

---

libraries/wutmalloc/wut_malloc.c

Some functions of the wutmalloc implementation do not set the errno value on error

wutmalloc: make sure to set errno properly on error

---

Makefile
include/nn/idb.h
include/nn/idb/IDBReader.h
include/nn/idb/idb_cpp.h
libraries/nn_idb/IDBReader.cpp
tests/test_compile_headers_common/test_compile_headers_list.h

nn::idb is a static lib to access the "icon database" found in the Wii U Menu common save directory ("BaristaIconDataBase.dat")

nn_idb: Implement icon database reading

---

include/padscore/kpad.h
include/padscore/wpad.h

Adds:
- `WPADLed`
- `WPADDpdMode`
- `WPADPeripheral`
- `WPADIsMplsAttached()`
- `WPADGetDataFormat()`
- `WPADControlLed()`
- `WPADControlDpd()`
- `WPADReadMemoryAsync()`
- `WPADWriteMemoryAsync()`
- `WPADReadExtReg()`
- `WPADWriteExtReg()`
- `WPADGetBLCalibration()`
- `KPADEnableMpls()`
- `KPADDisableMpls()`
- and more

A little more padscore

---

include/coreinit/stopwatch.h
include/coreinit/stopwatchatomic.h
tests/test_compile_headers_common/test_compile_headers_list.h

Adds the stopwatch functions and structs.
Named what should be `OSStopWatch` to `OSStopWatchAtomic` to avoid confusion with `OSStopwatch`

coreinit: add stopwatch.h and stopwatchatomic.h

---

include/nsysccr/cdc.h

Changed DRH state names, notably:
UNK0-> NORADIO (connected DRCs warn about poor connection and disconnect afterwards)
UNK1-> WII (connected DRCs enter wii mode without input)
UNK2-> [not renamed] (connected DRCs power off and when powered back on, enter wii mode)
UNK3-> NODRC (connected DRCs immediately power off; this mode can only be disabled by rebooting)
UNK7F-> [not renamed] ~~(this mode is not recognized on latest DRH firmware, comment added)~~
DRC EEPROM now defined as data instead of being unknown.
More info yet to be added. What I can say is that the DRC does not know its' own serial.
Initial dumps seem to show that the size is 5E0h bytes total with a filler hex-string of "DEADBABE" at the end (when dumping as DRC0 - dumping as DRC1 shows strange results)

More DRX definitions

---

include/nn/cfg/CTR.h
include/nn/uds.h
include/nn/uds/Cafe.h
include/nn/uds/NodeInformation.h
include/nn/uds/ScrambledLocalFriendCode.h
tests/test_compile_headers_common/test_compile_headers_list.h

This is an initial implementation of `nn::uds`, which can be used for communicating with nearby 3DS devices locally using local Wi-Fi. Not every function has been added on this PR due to either it being a low level function (such as making `Ioctlv` calls directly) or missing research. I would like suggestions as to whether the headers are well organized or how to improve them, these have also been organized in a way for future-proofing a `nn::dlp` implementation in the future, due to header dependencies.
`nn::uds` is essentially a C++ wrapper around the `/dev/udscntrl` IOSU, which only exposes the needed functionality for hosting a network. A lot of the concepts and structures are the same as on the 3DS implementation, to the extent where most the `Ioctlv` commands share the same value as …

nn/uds: Add initial headers

---

include/nn/dlp.h
include/nn/dlp/Cafe.h
tests/test_compile_headers_common/test_compile_headers_list.h

This is an initial implementation of Download Play (`nn_dlp`) on the Wii U. Research has revealed that there aren't any Wii U games that used this feature nor there could have been any, because the IOSU requires system archives that aren't present on the Wii U in order to initialize. For this reason, this requirement must be patched in order to utilize the library. At the time of writing, this plugin can be used to workaround this: https://github.com/DaniElectra/DlpPatcher
Homebrew that want to use this library **must** use Aroma 21 or later, as it adds the necessary permission group to let homebrew access DLP. Otherwise, the console would *crash* as it doesn't have permission to use DLP.
The name of the DLP child MUST be like this: `00040001XXXXXXYY.cia`, where `XXXXXX` is the input …

nn/dlp: Add initial headers

---

include/nn/dlp/Cafe.h

These functions were pointing to the `Server` implementation, and not the `ServerPrivate` one. Fix the typo using the correct `ServerPrivate` export instead.

nn/dlp: Fix Initialize functions on ServerPrivate

---

include/coreinit/screen.h

coreinit/screen: Swap row and column parameters in OSScreenPutFontEx

---

include/camera/camera.h

- CAMSetupInfo layout correction
- CAMMode and CAMEventData specifics
- More CamError values
- Add comments to functions

camera: corrections and comments

---

cafe/nn_acp.def
include/coreinit/mcp.h
include/nn/acp/device.h
include/nn/acp/save.h
include/nn/acp/title.h

ACPDeviceType values are based on a function in nn_acp.rpl which converts them to be used in `MCP_GetTitleInfoByTitleAndDevice` . 
MCPDeviceType matches the values as well <https://github.com/devkitPro/wut/blob/9a32ef1b658451e1bba97a18edb1c583eecf6cd1/include/coreinit/mcp.h#L64-L69>

nn_acp: Add various save related functions

---

include/camera/camera.h

It was meant to be the surface's buffer, rather than a pointer to the surface that is returned

camera: event argument correction

---

include/coreinit/performancemonitor.h
tests/test_compile_headers_common/test_compile_headers_list.h

- Add a declaration for `OSSetPerformanceMonitor()`.
- Define associated enums flags to use as arguments (derived from the PPC manual).
- Define inlined functions to read the performance registers.

Added `OSSetPerformanceMonitor()`.

---

include/nn/ac/ac_cpp.h
include/nn/result.h
include/nsysnet/netconfig.h

In `nsysnet/netconfig.h`:
- Changed type of `.ssid` in `NetConfWifiConfigData` to be a `char` array because it's a string.
- Fix typo in `NetConfInterface`: `.if_sate` -> `.if_state`.
In `nn/result.h`:
- Added a default constructor for `nn::Result`: we need to variables of this type to pass as an output argument to some functions.
In `nn/ac/ac_cpp.h`:
- Fixed wrong signature for `nn::ac::GetCloseStatus()`, and added the corresponding `nn::ac::Status` enum.
- Added a few more functions.
- Added the `nn::ac::Config` type alias to `NetConfCfg`.

Fix typo in nsysnet and add more `nn::ac` functions.

---

include/coreinit/debug.h

Based on https://github.com/decaf-emu/decaf-emu/blob/e6c528a20a41c34e0f9eb91dd3da40f119db2dee/src/libdecaf/src/cafe/libraries/coreinit/coreinit_osreport.h and additional RE.

coreinit/debug: Add OSSendFatalError

---

include/coreinit/cosreport.h
include/coreinit/debug.h
include/coreinit/internal.h
include/wut.h
libraries/libgfd/src/gfd.c
libraries/libwhb/include/whb/log.h
libraries/libwhb/src/crash.c
libraries/libwhb/src/gfx_heap.c
libraries/wutdevoptab/devoptab_fsa.cpp
libraries/wutdevoptab/devoptab_fsa_dirnext.cpp
libraries/wutdevoptab/devoptab_fsa_diropen.cpp
libraries/wutdevoptab/devoptab_fsa_fstat.cpp
libraries/wutdevoptab/devoptab_fsa_open.cpp
libraries/wutdevoptab/devoptab_fsa_read.cpp
libraries/wutdevoptab/devoptab_fsa_seek.cpp
libraries/wutdevoptab/devoptab_fsa_stat.cpp
libraries/wutdevoptab/devoptab_fsa_statvfs.cpp
libraries/wutdevoptab/devoptab_fsa_truncate.cpp
libraries/wutdevoptab/devoptab_fsa_write.cpp

This adds `WUT_FORMAT_PRINTF` to decorate printf-like functions.
Incidentally, this revealed a few debug prints that had the wrong number of arguments for the format string, or read the wrong number of bytes from an argument (in `devoptab_fsa_truncate.cpp`, that one was pretty bad.)
Debug prints were also changed to use `%p` for pointers. I don't think any of those cases could lead to crashes though.

Add `WUT_FORMAT_PRINTF` and fix some format string bugs.
