devkitPro/wut

tools/elf2rpl/main.cpp
=> Add SHT_RPL_IMPORT signatures to elf2rpl

tools/elf2rpl/main.cpp
Examining the order data is written in various RPXs and RPLs reveals that the data is written in a particular order (CRCs & FileInfo -> Data -> Load -> Code). This can be seen in in Sm4sh's readrpl output [before sorting](https://gist.github.com/shinyquagsire23/08223f687e17c6db68827c328094aefb) vs [after sorting](https://gist.github.com/shinyquagsire23/4133952d990fb3b427d47f645eecc6e1).
Edit: Example of data sorting before vs after against the Hello World sample: https://gist.github.com/shinyquagsire23/a42c2f54dac7ba04752ff265bf6071cd
=> Write in data in the order that loader expects it

tools/elf2rpl/main.cpp
This PR fixes a few issues with elf2rpl with regard to loader.elf on hardware. A summary of the fixes includes:
- Marking .rodata as RW (I'm not sure why this is needed? However it seems that most if not all RPXs and RPLs have it set as such).
- exports, strtab, symtab, and shstrtab must be at the beginning of Load memory
- Useless symbols (ie the _tramp symbols and others) need to be pruned out before generating relocations and symtab, strtab, shstrtab.
- FileInfo sizes as checked in loader.elf are based on the address ranges for each memory section rather than the collective sizes, with the exception of tempSize which is only an accumulation of RELA sizes.
Combined with #8 and #9, RPXs generated by wut should be able to be loaded on hardware using utilities such as loadiine.
=> Collective fixes for elf2rpl

include/vpad/input.h, rpl/Makefile, rpl/libvpad/Makefile, rpl/libvpad/config.h, rpl/libvpad/exports.h
Only adds basic input, however more functions can be added later.
=> Add basic vpad RPL imports

include/sysapp/launch.h, include/sysapp/switch.h, rpl/Makefile, rpl/libsysapp/Makefile, rpl/libsysapp/config.h, rpl/libsysapp/exports.h
Basic function definitions from wiiubrew, used for launching and switching apps (and exiting to menu on _Exit).
=> Add basic sysapp RPL imports

samples/pong/Makefile, samples/pong/src/draw.c, samples/pong/src/draw.h, samples/pong/src/memory.c, samples/pong/src/memory.h, samples/pong/src/pong.c, samples/pong/src/pong.h, samples/pong/src/program.c, samples/pong/src/program.h
A port of Relys' pong sample from libwiiu to wut. Uses OSScreen and basic VPAD, attempts to use sysapp for proper exiting but it is currently broken.
=> Add pong sample to samples/

samples/helloworld/Makefile, samples/helloworld/src/main.c, samples/pong/Makefile, samples/pong/src/program.c
Adds proper multitasking to both samples for app suspension to background, exiting. Requires #22
=> Add multitasking to samples

include/coreinit/filesystem.h, rpl/libcoreinit/fs_dev.c
This was intended to be in the main devoptab PR but got left out.
=> Add FSMountSource struct, use filesystem structs in devoptab

crt/memory.c
Somehow found a library which used this corner case.
=> Realloc should only return the allocated pointer if it is passed a nullptr to rellocate

include/coreinit/mcp.h, rpl/libcoreinit/exports.h
It works as long as you have your cos.xml permissions in line.
=> Add basic MCP coreinit imports

include/nsysnet/socket.h, include/proc_ui/procui.h, include/sysapp/launch.h, include/sysapp/switch.h, include/vpad/input.h
Fixed C++ defines and procui.h declarations
=> Fixed C++ defines and procui.h declarations

include/gx2/display.h, include/gx2/enum.h, include/gx2/mem.h, include/gx2/surface.h, rpl/libgx2/exports.h
Most of these are just basic necessities for GX2 homebrew.
=> Additional GX2 definitions from decaf-emu

crt/fs_dev.c
In my defense I'm not 100% sure if make clean actually cleans everything. I probably just forgot to actually make clean and never noticed it errored.
=> Fix fs_dev.c so that it actually compiles

crt/fs_dev.c
=> Allocate FSCmdBlock per-operation to avoid sharing conflicts between threads

include/coreinit/memory.h, include/coreinit/memorymap.h, include/proc_ui/procui.h, include/vpad/input.h
Heyo!
This is the first batch of Doxygen documentation for the wut headers - pulled from [earlier work on Decaf](https://github.com/QuarkTheAwesome/decaf-emu/commits/doc). I gave it the once-over, but if I missed anything (broken links, references to being in Decaf) please let me know!
Thanks!
-Ash
=> COS Docs: Pull stuff in from Decaf

include/proc_ui/procui.h
Bit more COS documentation stuff, ProcUI is mostly done now. Might need a few tweaks in terms of language and behaviour though.
Thanks!
-Ash
=> COS Docs: Most of ProcUI

include/vpad/input.h
Hey again! Another small batch of docs.
I'm starting to reach the edge of what I know about the VPAD lib - might make some kind of demo to try and learn about the gyro stuff - we'll see how that goes.
Thanks again,
-Ash
=> include/vpad: Documentation style tweaks, add VPADLcdMode, more docs

include/coreinit/cache.h, include/coreinit/core.h, include/coreinit/screen.h
Heyo!
Another batch of Doxygen docs. Hopefully I didn't make any typos this time!
Thanks again,
Ash
=> COS Docs: Add Doxygen for coreinit/cache, coreinit/core and coreinit/screen

include/sysapp/launch.h, include/sysapp/switch.h, include/sysapp/sysapp.dox
Hey again!
I know it's been a while, but here's sysapp. There's a few things I wasn't 100% on (specifically, the interaction with ProcUI is total assumption) but hey, it's something.
Thanks again,
Ash
=> include/sysapp: Add basic documentation

share/wut.mk
Heyo! This is a PR to add make support to wut.
**Rationale**:
cmake is awesome. If anything, writing this makefile has made me appreciate that more. However, some projects are adamantly against it - RetroArch is one of these projects, yet they could definitely benefit from using wut - heck, they're basically using it already! It makes sense to have make support in the toolchain to appeal to those kind of projects.
**How it works**:
At its simplest, using makefile wut looks something like this:
```makefile
simpleapp.rpx: main.o
include $(WUT_ROOT)/share/wut.mk
```
Of course, no app is quite this simple. Here's something a bit more involved:
```makefile
LDFLAGS += -lnsysnet $(WUT_NEWLIB_LDFLAGS)
CFLAGS += -Wall -O3
complexapp.rpx: src/main.o src/gfx/gfx.o src/gfx/texture.o
complexapp.rpx: …
```
=> Add make support to wut

include/nsysnet/socket.h, include/vpad/input.h
Added missing function declarations:
* inet_ntoa_r
* inet_ntop
* inet_pton
* VPADGetTPCalibratedPointEx
=> Add missing function declarations

share/wut_rules
See https://github.com/devkitPro/devkitppc-rules/blob/master/base_tools#L41 for more information.
=> Fix make V=1

include/coreinit/memory.h
- add function OSMemoryBarrier
- add function __OSZeroProcessMemory
- add function OSGetSharedData + enum OSSharedDataType
=> Changes in coreinit/memory.h

include/dmae/mem.h
- add function DMAEFillMemPhys
=> Add missing function to dmae/mem.h:

include/coreinit/cache.h
- add function OSMemoryBarrier
=> Add missing function to coreinit/cache.h

include/coreinit/cosreport.h, tests/test_compile_headers_common/test_compile_headers_list.h
- add enum COSReportLevel
- add enum COSReportModule
- add function COSVReport
- add function COSError
- add function COSInfo
- add function COSVerbose
- add function COSWarn
see decaf for reference:
- https://github.com/decaf-emu/decaf-emu/blob/dcd9bd1a084ac2806676ea1197c500edfe987f5a/src/libdecaf/src/cafe/libraries/coreinit/coreinit_cosreport.h
- https://github.com/decaf-emu/decaf-emu/blob/1dc2c3a27832c4c0bcfb6dcac3ce0e64532ddf62/src/libdecaf/src/cafe/libraries/coreinit/coreinit_enum.h
=> Add coreinit/cosreport.h

include/nn/swkbd/swkbd_cpp.h
This allows homebrew to create functions like
```
bool kbdVisible()
{
return nn::swkbd::GetStateInputForm() != nn::swkbd::State::Hidden;
}
void drawKbd()
{
if(kbdVisible())
{
nn::swkbd::DrawTV();
nn::swkbd::DrawDRC();
}
}
```
=> nn::swkbd::State: Rename Unknown0 to Hidden

include/coreinit/bsp.h, tests/test_compile_headers_common/test_compile_headers_list.h
- add enum BSPErrors
- add enum BSPHardwareVersions
- add function bspInitializeShimInterface
- add function bspGetHardwareVersion
See decaf for reference:
- https://github.com/decaf-emu/decaf-emu/blob/1dc2c3a27832c4c0bcfb6dcac3ce0e64532ddf62/src/libdecaf/src/ios/bsp/ios_bsp_enum.h
- https://github.com/decaf-emu/decaf-emu/blob/dcd9bd1a084ac2806676ea1197c500edfe987f5a/src/libdecaf/src/cafe/libraries/coreinit/coreinit_bsp.h
=> Add coreinit/bsp.h

samples/cmake/my_first_rpl/CMakeLists.txt, samples/cmake/my_first_rpl/exports.def, samples/cmake/my_first_rpl/my_first_rpl.c, samples/cmake/my_first_rpl/my_first_rpl.h, samples/cmake/my_first_rpl/my_first_rpx.c, share/wut.cmake, share/wut.toolchain.cmake
Generates a static import library and a linker script to link with that library using rplimportgen.
Updates the my_first_rpl sample to use this.
=> Add support for linking to user RPLs.

.github/workflows/ci.yml, include/gx2/debug.h, include/vpad/input.h
* Added definition for **VPADSetGyroDirReviseBase** in _input.h_.
* Removed the sudo in _ci.yml_, this is not required when using a Docker container.
* Added missing doxygen comments in _debug.h_.
=> Add definition for VPADSetGyroDirReviseBase

include/nn/result.h
Although bit fields often work nicely, the bit fields in nn::Result had the order of accessed bits swapped, compiler's target endianness affects the order of what bits are accessed in struct bitfields.
It was proper for little endian targets, but not big endian.
Using bit shifts instead, to also allow general portability.
=> Small fixup on nn::Result

include/coreinit/filesystem.h, libraries/libwhb/src/file.c, libraries/libwhb/src/sdcard.c, libraries/wutdevoptab/devoptab_fs_chdir.c, libraries/wutdevoptab/devoptab_fs_chmod.c, libraries/wutdevoptab/devoptab_fs_close.c, libraries/wutdevoptab/devoptab_fs_dirclose.c, libraries/wutdevoptab/devoptab_fs_dirnext.c, libraries/wutdevoptab/devoptab_fs_diropen.c, libraries/wutdevoptab/devoptab_fs_dirreset.c, libraries/wutdevoptab/devoptab_fs_fstat.c, libraries/wutdevoptab/devoptab_fs_fsync.c, libraries/wutdevoptab/devoptab_fs_mkdir.c, libraries/wutdevoptab/devoptab_fs_open.c, libraries/wutdevoptab/devoptab_fs_read.c, libraries/wutdevoptab/devoptab_fs_rename.c, libraries/wutdevoptab/devoptab_fs_rmdir.c, libraries/wutdevoptab/devoptab_fs_seek.c, libraries/wutdevoptab/devoptab_fs_stat.c, libraries/wutdevoptab/devoptab_fs_truncate.c, libraries/wutdevoptab/devoptab_fs_unlink.c, libraries/wutdevoptab/devoptab_fs_write.c, samples/cmake/swkbd/main.cpp
Values taken from [decaf](https://github.com/decaf-emu/decaf-emu/blob/131aeb14fccff8461a5fd9f2aa5c040ba3880ef5/src/libdecaf/src/cafe/libraries/coreinit/coreinit_enum.h#L299)
=> coreinit/filesystem: Add FSErrorFlag

include/sndcore2/core.h
=> Add AXDeregisterAppFrameCallback

include/coreinit/time.h, include/vpad/input.h
Added:
* VPADDisablePowerButton
* VPADEnablePowerButton
* VPADBASEGetHeadphoneStatus
* VPADBASEGetGameControllerMode
* VPADBASESetGameControllerMode
* VPADBASEGetPowerButtonPressStatus
* VPADBASESetPowerButtonPressStatus
* VPADBASESetPowerButtonDisableMode
=> Add definitions

include/netdb.h, include/nsysnet/_netdb.h, include/sys/filio.h, include/sys/ioccom.h, include/sys/ioctl.h, include/sys/socket.h, libraries/wutsocket/addrinfo.c, libraries/wutsocket/host.c, libraries/wutsocket/hostid.c, libraries/wutsocket/ioctl.c, libraries/wutsocket/stubs.c, libraries/wutsocket/wut_socket_common.c
As discussed in https://github.com/devkitPro/wut/pull/136
=> wutsocket: add more missing functions

include/nsysuhs/nsysuhs.dox, include/nsysuhs/uhs.h, include/nsysuhs/uhs_usbspec.h, tests/test_compile_headers_common/test_compile_headers_list.h
Work in progress header for the nsysuhs.rpl
Most parts are taken from the [libwiiu repo](https://github.com/wiiudev/libwiiu/blob/master/libwiiu/src/uhs.h)
=> WIP: nsysuhs: Add header for nsysuhs.rpl 

include/nn/sl.h, include/nn/sl/FileStream.h, include/nn/sl/LaunchInfoDatabase.h, include/nn/sl/sl_cpp.h, tests/test_compile_headers_common/test_compile_headers_list.h
Probably not the cleanest code, but thats the best I could do :)
=> SL: Add missing header

.github/workflows/doc.yml, include/nn/swkbd/swkbd_cpp.h, include/padscore/kpad.h, include/vpad/input.h, samples/cmake/swkbd/main.cpp
Co-Authored-By: Fangal-Airbag <77993079+Fangal-Airbag@users.noreply.github.com>
=> Add more fields to nn::swkbd

include/coreinit/debug.h, include/coreinit/memory.h, include/coreinit/transition.h, include/sndcore2/core.h, tests/test_compile_headers_common/test_compile_headers_list.h
Some function delcrations of functions used in the root.rpx
=> Add various functions used in root.rpx

include/coreinit/filesystem.h, include/coreinit/userconfig.h, include/nn/act/client_cpp.h
Just a few function that get used in SCI
I'm probably gonna finish the SCI Implementation in a few days or so
=> Add functions used in SCI lib

include/nn/fp.h, include/nn/fp/fp_cpp.h
Currently some structs are missing and i havent found a way of testing it with homebrew
RE'd most stuff out of games with debug symbols and frd.rpx(Friend list)
=> Add nn::fp lib

include/coreinit/filesystem.h, include/coreinit/filesystem_fsa.h, include/coreinit/ipcbufpool.h, tests/test_compile_headers_common/test_compile_headers_list.h
Accidentally closed the old PR...
=> Add FSA structs and function declarations

include/proc_ui/memory.h, include/proc_ui/procui.h, tests/test_compile_headers_common/test_compile_headers_list.h
Adds all of the missing Proc UI functions.
=> Proc UI: Add missing functions

include/coreinit/filesystem.h
This PR just changes the last missing field in the struct :)
=> Update FSStateChangeParams and add offset checks

include/nfc/nfc.dox, include/nfc/nfc.h, include/nn/nfp/nfp_cpp.h, tests/test_compile_headers_common/test_compile_headers_list.h
Based on nfc.rpl, ntag.rpl and the gamepad firmware.
=> nfc: Add initial header

Makefile, libraries/nn_idb/src/IDBReader.cpp
=> nn_idb: Fix copy headers, fix nn::idb::IDBReader::Initialize

include/padscore/kpad.h, include/padscore/wbc.h, include/padscore/wpad.h, tests/test_compile_headers_common/test_compile_headers_list.h
This PR adds a number of functions, structs and enums, that were missing from the padscore library.
=> Various additions to padscore

include/coreinit/bsp.h
Copied from https://github.com/NWPlayer123/IOSU/blob/master/ios_bsp/libraries/bsp_entity/include/bsp_entity_enum.h .
=> bsp: Add all BSP return values
